# This compose file can be used to run an example postgres database in remote machine to test db backup
version: "3.7"

services:
  postgres-demo:
    image: postgres
    container_name: ${docker_container_name}
    environment:
      POSTGRES_USER: ${db_username}
      POSTGRES_PASSWORD: ${db_password}
    ports:
      - "5432:5432"
    volumes:
      - /dump:/dump
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
